# Generated by Django 4.2 on 2025-03-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_totalcount"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
            preserve_default=False,
        ),
    ]
