# Generated by Django 4.2 on 2025-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_remove_payment_user_payment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
