# Generated by Django 4.2 on 2025-04-19 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specification",
            options={
                "verbose_name": "Спецификация",
                "verbose_name_plural": "Спецификации",
            },
        ),
    ]
