# Generated by Django 4.2 on 2025-03-24 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totalCount",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name=django.core.validators.MinValueValidator(1),
            ),
        ),
    ]
