# Generated by Django 4.2 on 2025-03-24 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_totalcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalCount",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
